---
title: "BedCharacteristics_Oct2023Survey"
author: "Mariah Kachmar"
date: "12/13/2023"
output: html_document
updated: 1/30/24
description: This R code is used to important and summarize bed characteristics (height, area, rugosity, density, and coverage) data from the LISS Oyster Health Project's October 2023 oyster population surveys at Ash Creek and Fence Creek intertidal sites in Connecticut and Goldstar Beach and Laurel Hollow subtidal sites in New York. 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = 'C:/Users/mariah.kachmar/documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Mariah's
knitr::opts_knit$set(root.dir = 'C:/Users/kyra.lenderman/documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Kyra's

library(readr)
library(dplyr)
library(Rmisc)
```




```{r}

data_all <- list.files(path = "Field_Data_Biological/raw_data/Characteristics",                           # Identify all CSV files
  pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows()
data_all

as.data.frame(data_all)

 
data_all <- data_all %>% filter(!is.na(Date))
data_all
```
#Bed height NY sites
 
```{r}
#Summary of bed height at each site - Goldstar & Laurel Hollow

Bed_height_NY <- data_all %>%
  filter(!is.na(Live_count) & !is.na(Box_count) & !is.na(Gaper_count) & !is.na(Bed_height))
Bed_height_NY 

bedheight_summary_NY <- summarySE(data = Bed_height_NY, measurevar = "Bed_height", groupvars = c( "Date", "Site"))

bedheight_summary_NY

#write.csv(bedheight_summary, "C:/Users/mariah.kachmar/Documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance/Field_Data_Biological/Output/BedHeight_AllSite.csv", row.names=FALSE)
```

#oyster density metrics
## Need to fix this somewhere. The output is not giving just a single number for each site. 
```{r}

#data_all <- data_all %>%
#  filter(!is.na(Live_count) & !is.na(Box_count) & !is.na(Gaper_count))
#data_all  

density_live_sum <- summarySE(data = data_all, measurevar = "Live_count", groupvars = c(  "Site"))
density_live_sum
density_live_sum <- density_live_sum %>%
  mutate(Count = Live_count) %>%
  select(-Live_count)


density_box_sum <- summarySE(data = data_all, measurevar = "Box_count", groupvars = c( "Site"))
density_box_sum <- density_box_sum %>%
  mutate(Count = Box_count) %>%
  select(-Box_count)
density_box_sum

density_gaper_sum <- summarySE(data = data_all, measurevar = "Gaper_count", groupvars = c( "Site"))
density_gaper_sum <- density_gaper_sum %>%
  mutate(Count = Gaper_count) %>%
  select(-Gaper_count)



density_summary<- rbind(density_gaper_sum, density_box_sum, density_live_sum)
density_summary

#sum total number of oysters counted per quadrat
 


```


```{r}
sessionInfo()
```