#test

---
title: "QAQC_PopulationSurveyMetrics"
author: "Meghana Parikh"
date: "2023-06-29"
output: html_document
---

```{r, setup, include=FALSE}

knitr::opts_knit$set(root.dir = 'C:/Users/meghana.parikh/Documents/GitHub/EAD-ASEB_EPA_LISS_Disease_Surveillance/Field_Data_Biological')


install.packages("tidyverse")
install.packages("gtools")
install.packages("Rmisc")
library(gtools)
library(readxl)
library(plyr)
library(dplyr)
library(lubridate)
library(Rmisc)

```

```{r}

#### need to work on this chunk to read in all files at once - not ready to use
data_all <- list.files(path = "C:/Users/meghana.parikh/Documents/GitHub/EAD-ASEB_EPA_LISS_Disease_Surveillance/Field_Data_Biological",                                                               
  pattern = "*.xlsx", full.names = TRUE) %>%         # Identify all xlsx files
  lapply(read_excel) %>%                            # Store all files in list
data_all                                            # Print data to RStudio console

as.data.frame(data_all)                            # Convert tibble to data.frame





```

```{r}

#read in all population survey sheets 


#June 2023
shellsize <- read_excel("C:\\Users\\meghana.parikh\\Documents\\GitHub\\EAD-ASEB_EPA_LISS_Disease_Surveillance\\Field_Data_Biological\\qry_2023-06_Survey_ShellSize.xlsx",
                     sheet = 1, col_names = TRUE) 

quadratdensity <- read_excel("C:\\Users\\meghana.parikh\\Documents\\GitHub\\EAD-ASEB_EPA_LISS_Disease_Surveillance\\Field_Data_Biological\\qry_2023-06_Survey_QuadratDensity.xlsx",
                     sheet = 1, col_names = TRUE) 

rugosity <- read_excel("C:\\Users\\meghana.parikh\\Documents\\GitHub\\EAD-ASEB_EPA_LISS_Disease_Surveillance\\Field_Data_Biological\\qry_2023-06_Survey_Rugosity.xlsx",
                     sheet = 1, col_names = TRUE) 

BedHeight <- read_excel("C:\\Users\\meghana.parikh\\Documents\\GitHub\\EAD-ASEB_EPA_LISS_Disease_Surveillance\\Field_Data_Biological\\qry_2023-06_Survey_BedHeight.xlsx",
                     sheet = 1, col_names = TRUE) 
```

```{r}
#oyster density metrics 


#sum total number of oysters counted per quadrat
quadratdensity$AllCount_Total <- rowSums(quadratdensity[, c("LiveCount_Total", "BoxCount_Total", "GaperCount_Total")])

#summary of each oyster type by site. output = Site, N, Mean, stnd dev, stnd error, and confidence interval
all_density_SE <-summarySE(data = quadratdensity, measurevar = "AllCount_Total", groupvars=c("Site_Name"))
live_density_SE <- summarySE(data = quadratdensity, measurevar = "LiveCount_Total", groupvars=c("Site_Name"))
box_density_SE <-summarySE(data = quadratdensity, measurevar = "BoxCount_Total", groupvars=c("Site_Name"))
gaper_density_SE <-summarySE(data = quadratdensity, measurevar = "GaperCount_Total", groupvars=c("Site_Name"))

#calculate percent standard error as 100*se/mean
all_density_SE$PSE_all <- 100*(all_density_SE$se/all_density_SE$AllCount_Total)
live_density_SE$PSE_live <- 100*(live_density_SE$se/live_density_SE$LiveCount_Total)
box_density_SE$PSE_box <- 100*(box_density_SE$se/box_density_SE$BoxCount_Total)
gaper_density_SE$PSE_gaper <- 100*(gaper_density_SE$se/gaper_density_SE$GaperCount_Total)


#join into 1 table 
densitysummary <- subset(all_density_SE, select = -c(sd,se,ci)) %>%
    left_join(subset(live_density_SE, select = -c(N,sd,se,ci)), by = "Site_Name") %>%
    left_join(subset(box_density_SE, select = -c(N,sd,se,ci)), by = "Site_Name") %>%
    left_join(subset(gaper_density_SE, select = -c(N,sd,se,ci)), by = "Site_Name") %>%

#renaming for clarity. need to use dplyr:: because another package is overriding the function
#densitysummary <- densitysummary %>%
    dplyr::rename(
      AllCount_Mean = AllCount_Total,
      LiveCount_Mean = LiveCount_Total,
      BoxCount_Mean = BoxCount_Total, 
      GaperCount_Mean = GaperCount_Total, 
      NumQuad = N) %>%
  
#calculate completeness as 100*N/12, where 12 is the desired number of quadrats per site 
  mutate(PercentComplete_Quad = ((NumQuad/12)*100) )


write.csv(densitysummary, "C:/Users/meghana.parikh/Documents/GitHub/EAD-ASEB_EPA_LISS_Disease_Surveillance/Field_Data_Biological\\populationdensity_summary.csv", row.names=FALSE)
#note that PSE is >20 percent at Ash Creek, and at Fence creek in box and gaper categories. This is due to the different levels of sampling. Need to redo with categories 


```



```{r}

#oyster size distribution

#finding the empty values - these are oyster samples collected for lab use I think?
emptyvalues <- shellsize %>% filter(is.na(Height_mm))
      
shellsize_all <- 
  shellsize %>% group_by(Site_Name) %>%
  summarise(
    median_height=median(Height_mm, na.rm = TRUE), 
    min_height=min(Height_mm, na.rm = TRUE), 
    max_height=max(Height_mm, na.rm = TRUE), 
    Q1=quantile(Height_mm,probs = 0.25, na.rm = TRUE),
    Q3=quantile(Height_mm,probs = 0.75, na.rm = TRUE))%>%
  mutate(SpecimenType = "All")

shellsize_live <- 
  shellsize %>% filter(SpecimenType=="Live") %>%
   summarise(
    median_height=median(Height_mm, na.rm = TRUE), 
    min_height=min(Height_mm, na.rm = TRUE), 
    max_height=max(Height_mm, na.rm = TRUE), 
    Q1=quantile(Height_mm,probs = 0.25, na.rm = TRUE),
    Q3=quantile(Height_mm,probs = 0.75, na.rm = TRUE))%>%
  mutate(SpecimenType = "Live")

shellsize_box <- 
  shellsize %>% filter(SpecimenType=="Box") %>%
   summarise(
    median_height=median(Height_mm, na.rm = TRUE), 
    min_height=min(Height_mm, na.rm = TRUE), 
    max_height=max(Height_mm, na.rm = TRUE), 
    Q1=quantile(Height_mm,probs = 0.25, na.rm = TRUE),
    Q3=quantile(Height_mm,probs = 0.75, na.rm = TRUE))%>%
  mutate(SpecimenType = "Box")

shellsize_gaper <- 
  shellsize %>% filter(SpecimenType=="Gaping") %>%
   summarise(
    median_height=median(Height_mm, na.rm = TRUE), 
    min_height=min(Height_mm, na.rm = TRUE), 
    max_height=max(Height_mm, na.rm = TRUE), 
    Q1=quantile(Height_mm,probs = 0.25, na.rm = TRUE),
    Q3=quantile(Height_mm,probs = 0.75, na.rm = TRUE))%>%
  mutate(SpecimenType = "Gaper")

#rbind together 

shellsize_summary <- rbind(shellsize_all, shellsize_live, shellsize_box, shellsize_gaper)

#size distribution summary
#note that calculating PSE and accuracy do not make sense for size distributions. Will need to figure out new metrics for the QAPP
write.csv(shellsize_summary, "C:/Users/meghana.parikh/Documents/GitHub/EAD-ASEB_EPA_LISS_Disease_Surveillance/Field_Data_Biological\\shellsize_summary.csv", row.names=FALSE)

  
```


```{r}
```
