---
title: "Raw_plotting_HOBO"
author: "Mariah Kachmar"
date: "1/19/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Load libraries

```{r load_libraries, include = TRUE}
# load libraries - notes show the install command needed to install (pre installed)
# Plotting
library(ggplot2)
library(dplyr)
library(gplots)
library(RColorBrewer)
library(ggpubr)
library(stringr)
library(lubridate)
library(readr)
library(reshape2)
library(readr)
library(tidyr)
```

#### Set path
#### Set path for Mariah K. 
```{r set the path out, include = TRUE}
path_out <-'C:/Users/mariah.kachmar/Documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance/Sonde_Data/output'
```

#### Fence Creek ####
```{r}
FENC_HOBO_23 <- read_csv("C:\\Users\\mariah.kachmar\\Documents\\Github\\EAD-ASEB_EPA_LISS_Disease_Surveillance\\HOBO_Data\\112023_FENC_HOBO.csv", col_names = TRUE)   

as.data.frame(FENC_HOBO_23)



#Change column names

FENC_HOBO_23 <- FENC_HOBO_23 %>%
  dplyr::rename(Temperature = `Ch:1 - Temperature   (°C)`) %>%
  dplyr:: rename(Date_Time = `Date-Time (EST/EDT)`)
FENC_HOBO_23

FENC_HOBO_23$Date_Time <- as.character(FENC_HOBO_23$Date_Time)
date_time <- strsplit(FENC_HOBO_23$Date_Time, " ")  # Split at the space
FENC_HOBO_23$Date <- sapply(date_time, "[[", 1)  # Extract date
FENC_HOBO_23$Time <- sapply(date_time, function(x) {
  if(length(x) >= 2) {
    x[[2]]  # Extract the second element if it exists
  } else {
    NA  # Assign NA if the vector is too short
  }
})
print(FENC_HOBO_23)

## removing unneeded columns with NAs

FENC_HOBO_23 <- FENC_HOBO_23 %>%
  dplyr::select( -c("Host Connected", "Water Detect", "Button Down", "Button Up", "End of File"))

FENC_HOBO_23 <- na.omit(FENC_HOBO_23)

#### Lets look at the data 

ggplot(FENC_HOBO_23, aes(Date_Time, Temperature)) + geom_point()


# Hourly Means 

FENC_means <- FENC_HOBO_23 %>%
  mutate(Date_Time = as.POSIXct(substr(Date_Time, 1, 13), format = "%m/%d/%Y %H")) %>% # Adjust the date format
  tidyr::pivot_longer(cols = c("Temperature"), names_to = "variable", values_to = "value") %>%
  dplyr::group_by(Date_Time, variable) %>%
  dplyr::summarise(mean_value = mean(value),sd_value = sd(value),se_value = sd(value) / sqrt(n())) 

FENC_means
  plot<- FENC_means %>%
    ggplot(aes(Date_Time, mean_value))+ geom_point() + 
    geom_line(size = 0.2, position=position_dodge(.4))+
    #scale_color_manual(values = "grey38")+
              scale_shape_manual(values=c(21, 22, 24, 25)) + 
              scale_fill_manual(values=c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
              geom_errorbar(aes(ymin=(mean_value)-(se_value), 
                                ymax=(mean_value)+(se_value)), 
                            width=0,position=position_dodge(.4))+
     ggtitle("Fence Creek HOBO Temperature Data ") +
              labs(x = "Time", y = "Temperature") +
              theme_classic()
plot

pdf(paste0(path_out,"/outputs/raw_plots/FENC_HOBO.pdf"), height = 7, width = 14)
print(plot)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

```{r}
sessionInfo()
```